### ISSUE TITLE
最新的创建的本地docker+Vercel回报405 Method NOT Allowed

### ISSUE THREAD

**Issue by Alex-coffen** [babaohuang/GeminiProChat#145]
### How is Gemini Pro Chat deployed?

Docker

### Describe the bug

什么都没有变，只是把git pull到最新，重新建了docker image（我命名为v2），docker compose.yaml不变，在网页上问问题会405.

root@ubuntu:~/gemini/GeminiProChat# docker logs geminiprochat
Starting service...
Running script...
Server listening on http://0.0.0.0:3000
GoogleGenerativeAIError: [405 Method Not Allowed]
    at makeRequest (file:///usr/src/node_modules/.pnpm/@fuyun+generative-ai@0.1.3/node_modules/@fuyun/generative-ai/dist/index.mjs:214:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContentStream (file:///usr/src/node_modules/.pnpm/@fuyun+generative-ai@0.1.3/node_modules/@fuyun/generative-ai/dist/index.mjs:517:22)

但是切换回去v1，使用没有问题

### Console Logs

version: '3'

services:
  geminiprochat:
    #build: .
    container_name: geminiprochat
    restart: always
    ports:
      - "13030:3000"
    environment:
      - GEMINI_API_KEY=AIzaSyDnX8ALr453WFXb-XXXX
      # - HTTPS_PROXY=YOUR_HTTPS_PROXY
      - API_BASE_URL=https://XXX.app
      # - HEAD_SCRIPTS=YOUR_HEAD_SCRIPTS
      # - PUBLIC_SECRET_KEY=YOUR_SECRET_KEY
      # - SITE_PASSWORD=YOUR_SITE_PASSWORD
      # - OPENAI_API_MODEL=YOUR_OPENAI_API_MODEL
    image: geminiprochat:v2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Alex-coffen** [comment]
明白了，最新的代码只能和netlify一起用了。。
