### ISSUE TITLE
Send button not working when submitting request on my fork.

### ISSUE THREAD

**Issue by codenamedpkt** [babaohuang/GeminiProChat#149]
### What operating system are you using?

All

### What browser are you using?

Chrome

### Describe the bug

Send button did output results once user submitted. Deployed in Vercel and Netlify proxied for ease of user which country did not supported.

### What prompt did you enter?

您好，我係bla bla bla，特別高興認識Gemini Pro AI。

### Console Logs

rocket-loader.min.js:1 A preload for 'https://gemini.example.xyz/_astro/hoisted.fe1ded4d.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
t.activateScript @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
P @ rocket-loader.min.js:1
callback @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
load (async)
t.runOnLoad @ rocket-loader.min.js:1
x @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
Generator.965bb329.js:38 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at Generator.965bb329.js:38:647
    at Generator (Generator.965bb329.js:38:2213)
    at web.9c391a5e.js:1:5148
    at y (web.9c391a5e.js:1:1075)
    at ve (web.9c391a5e.js:1:5142)
    at d.renderId (client.0e663382.js:1:559)
    at web.9c391a5e.js:1:6461
    at B.r (web.9c391a5e.js:1:458)
    at A (web.9c391a5e.js:1:3298)
    at B (web.9c391a5e.js:1:499)
(anonymous) @ Generator.965bb329.js:38
Generator @ Generator.965bb329.js:38
(anonymous) @ web.9c391a5e.js:1
y @ web.9c391a5e.js:1
ve @ web.9c391a5e.js:1
d.renderId @ client.0e663382.js:1
(anonymous) @ web.9c391a5e.js:1
B.r @ web.9c391a5e.js:1
A @ web.9c391a5e.js:1
B @ web.9c391a5e.js:1
ge @ web.9c391a5e.js:1
ye @ web.9c391a5e.js:1
Oe @ web.9c391a5e.js:1
(anonymous) @ client.0e663382.js:1
hydrate @ VM31:1
e @ VM31:1
await in e (async)
start @ VM31:1
childrenConnectedCallback @ VM31:1
connectedCallback @ VM31:1
(anonymous) @ VM31:1
(anonymous) @ VM31:1
t.activateScript @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
load (async)
t.runOnLoad @ rocket-loader.min.js:1
x @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
gemini.alicepoon1993.xyz/:1 The resource https://gemini.example.xyz/_astro/hoisted.fe1ded4d.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SauerkrautFFish** [comment]
我想问下，gemini不是不支持中文吗，请问楼主如何实现能支持中文的gemini。

**Comment by codenamedpkt** [comment]
目前，只有Gemini Pro支持中文，不過您可以嘗試用Gemini Ultra大模型用中文提問，不過有可能輸出英文，也有可能用不了。 @SauerkrautFFish
