### ISSUE TITLE
使用代理出错

### ISSUE THREAD

**Issue by sunchongwei** [babaohuang/GeminiProChat#15]
### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the bug

配置文件.env设置了代理http://127.0.0.1:10809，但是无法使用
![image](https://github.com/babaohuang/GeminiProChat/assets/36410461/1d57a1ce-52f7-4e8f-90db-ab3fa49cd467)

Server listening on http://0.0.0.0:3000
Error: [GoogleGenerativeAI Error]: Text not available. Response was blocked due to SAFETY
    at response.text (file:///usr/src/node_modules/.pnpm/@google+generative-ai@0.1.1/node_modules/@google/generative-ai/dist/index.mjs:250:19)
    at Object.start (file:///usr/src/dist/server/chunks/pages/generate.ts.06be4226.mjs:76:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sendMessageStream() was unsuccessful. Response was blocked due to SAFETY. Inspect response object for details.
Error: [GoogleGenerativeAI Error]: Text not available. Response was blocked due to SAFETY
    at response.text (file:///usr/src/node_modules/.pnpm/@google+generative-ai@0.1.1/node_modules/@google/generative-ai/dist/index.mjs:250:19)
    at Object.start (file:///usr/src/dist/server/chunks/pages/generate.ts.06be4226.mjs:76:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sendMessageStream() was unsuccessful. Response was blocked due to SAFETY. Inspect response object for details.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by babaohuang** [comment]
`API_BASE_URL`要参考这个nginx配置文件，在google支持的服务器上部署一个反代

```
server {
    listen       8888;
    server_name  xx.xx.xx.xx;

    proxy_http_version  1.1;
    proxy_set_header    Host generativelanguage.googleapis.com;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass https://generativelanguage.googleapis.com;
        proxy_ssl_server_name on;
    }
}
```
部署好之后把server_name填在`API_BASE_URL`

**Comment by antergone** [comment]
自己部署一个Vercel Edge，把API_BASE_URL换成对应域名即可。https://simonmy.com/posts/使用vercel反向代理google-palm-api.html
