### ISSUE TITLE
after deploying ，VPS log show Error: [GoogleGenerativeAI Error]: Text not available. Response was blocked due to SAFETY

### ISSUE THREAD

**Issue by Teda9** [babaohuang/GeminiProChat#70]
### How is Gemini Pro Chat deployed?

Docker

### Describe the bug

I deploy it in my cloudcone VPS ， and it does not work

### Console Logs

Server listening on http://0.0.0.0:3000
Error: [GoogleGenerativeAI Error]: Text not available. Response was blocked due to SAFETY
    at response.text (file:///usr/src/node_modules/.pnpm/@fuyun+generative-ai@0.1.3/node_modules/@fuyun/generative-ai/dist/index.mjs:259:19)
    at Object.start (file:///usr/src/dist/server/chunks/pages/generate.ts.2a0d54ba.mjs:45:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sendMessageStream() was unsuccessful. Response was blocked due to SAFETY. Inspect response object for details.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ZhangWei-KUMO** [comment]
I also meet same error.when I ask Gemini to translate "been killed by a Japanese sh his funeral was front page news in American newspapers then he was forgotten only decades later it was realized that Freddy John falo was likely the first American serviceman to be killed in the struggle that eventually became World War II still at least in China and in Chinese communities around the world the courage of the Chinese troops fighting in Shanghai prompted a new sense of" into Chinese,it responses this error
